# change to your project with compute time available
project: x77
queue: normal
walltime: 02:00:00
jobname: mom6_panan_12
#ncpus: 962
#jobfs: 10GB
ncpus: 1778
jobfs: 10GB

# change to a project you have access to
# shortpath: x77

model: mom6
input:
        #    - /g/data/x77/cy8964/mom6/input/input-8km-SIS2/
    - /g/data/x77/cy8964/mom6/input/input-8km-SIS2/Vertical_coordinate_125.nc
    - /g/data/x77/cy8964/mom6/input/input-8km-SIS2/topog_Charrassin_regridded_cropped.nc
    - /g/data/x77/cy8964/mom6/input/input-8km-SIS2/WOA_IC_bfilled_smoothedland_pottemp.nc
    - /g/data/x77/cy8964/mom6/input/input-8km-SIS2/topog_Charrassin_sea_ice_from_iceelev_no_edits_new190825.nc
    - /g/data/x77/cy8964/mom6/input/input-8km-SIS2/topog_Charrassin_open_cavity_noGL5m_new190825.nc
    - /g/data/x77/cy8964/mom6/input/input-8km-SIS2/ice_thickness_Charrassin_regridded_cropped_add_area_where_iceelev_noGL5m_new190825.nc
    - /g/data/x77/cy8964/mom6/input/input-8km-SIS2/mask_from_topog_Charrassin_sea_ice_from_iceelev_no_edits_new190825
    - /g/data/ik11/inputs/mom6/regrid_runoff/
    - /g/data/ik11/inputs/JRA-55/RYF/v1-3/
exe: /scratch/x77/cy8964/mom6/setup-mom6-nci-executable/MOM6-SIS2-c478543
#/g/data/ik11/inputs/mom6/bin/symmetric_FMS2-e7d09b7
#/g/data/x77/ahg157/exes/MOM6_SIS2/MOM6-aledbg-38a7d55
#/g/data/ik11/inputs/mom6/bin/symmetric_FMS2-e7d09b7
# /g/data/x77/ahg157/exes/MOM6_SIS2/MOM6-aledbg-38a7d55
#/g/data/x77/ahg157/exes/MOM6_SIS2/MOM6-dbg-e9dbc6c
#/g/data/ik11/inputs/mom6/bin/symmetric_FMS2-e7d09b7

collate: false
runlog: true
storage:
  gdata:
    - ik11
    - x77

platform:
  nodesize: 48

mpi:
  module: openmpi/4.1.2
