format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res.nc
  hashes:
    binhash: 7a76bd8627fc2fdf650d83110c513f53
    md5: f2f5e3801ec47acbc62fefa21242ae55
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_1.nc
  hashes:
    binhash: 3cf24d917e166f7eafb25e193213311e
    md5: 535971dc65b6342eb057efa7609090a1
work/INPUT/MOM.res_10.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_10.nc
  hashes:
    binhash: 9f25a4a3882cdf059aa1616be5bc316d
    md5: c9d067e974c02bc63a43c58ae41ef5ca
work/INPUT/MOM.res_11.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_11.nc
  hashes:
    binhash: 0e44cdf57707214e244585888ec2c11e
    md5: 3bcb0b2d261da89b3a33fda915e8a485
work/INPUT/MOM.res_12.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_12.nc
  hashes:
    binhash: 964a83dbdeb15e079cad4f837cc1eb49
    md5: 8b1ebb366e46efcb9296cca12054dfcf
work/INPUT/MOM.res_13.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_13.nc
  hashes:
    binhash: ab487f6f884f405c73ce3bf181170d09
    md5: 39e0cb013d2ed85e7d4503f7cc62c7d3
work/INPUT/MOM.res_14.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_14.nc
  hashes:
    binhash: e304ab53e9ebc4d091bed896039589c6
    md5: 1ddb18470b77d857781dbbd19c52ff33
work/INPUT/MOM.res_15.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_15.nc
  hashes:
    binhash: b729ec707ec8e33b49b28d4d72a616a1
    md5: acee808ccdf324bc70503bd5d63669c5
work/INPUT/MOM.res_16.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_16.nc
  hashes:
    binhash: 06a25dc834bf5d27aef84e5bacc53cd9
    md5: b58537f794b93211977bc53d7c050736
work/INPUT/MOM.res_17.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_17.nc
  hashes:
    binhash: a008ceee3ce6929574f7ddc932f7982f
    md5: fc287792565c91d03a44f94d5ba6f3ef
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_2.nc
  hashes:
    binhash: f8bd61606fc6755dac73bcf7265cea94
    md5: e154b6524a1a7ec4b4509681fcd7f1b9
work/INPUT/MOM.res_3.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_3.nc
  hashes:
    binhash: cfc44b709af1e712c89a7bf1135728cc
    md5: dc1575097e13623fc0846b40946d3390
work/INPUT/MOM.res_4.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_4.nc
  hashes:
    binhash: adb009340e7483337a454203f344fb3f
    md5: dcf0727f3b9119a296d1e7df54ccebab
work/INPUT/MOM.res_5.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_5.nc
  hashes:
    binhash: 39357d5c53a53846e10b4112987372e1
    md5: 4a40e5c75442ea6129c1f2820c59ff31
work/INPUT/MOM.res_6.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_6.nc
  hashes:
    binhash: 6214003006682817d9cdbd89a4a9bbb8
    md5: 188347c1094c214b3166bfdacd8764be
work/INPUT/MOM.res_7.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_7.nc
  hashes:
    binhash: 4a18f875ef33caf7a96be19523b22725
    md5: 87e64674aedcbd479eac3e096f53657d
work/INPUT/MOM.res_8.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_8.nc
  hashes:
    binhash: 5fd95b36b132d6b9ffa23de15e270ee4
    md5: b4ed130ce8c4e1378bbc13278baca868
work/INPUT/MOM.res_9.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/MOM.res_9.nc
  hashes:
    binhash: 23d12761ce253f9c920e7c0d8a7def70
    md5: 8096e12ab98af7b8dd66680155475d81
work/INPUT/Shelf.res.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/Shelf.res.nc
  hashes:
    binhash: 12659803788898dd5572d63c80478532
    md5: 34078165a507b52b3b3e8f7975720dd4
work/INPUT/coupler.res:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/coupler.res
  hashes:
    binhash: 9bc4c4dd50f3ecf884575e476ee9dd96
    md5: 8851b0cdf749466ba45cd473399777c1
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/ice_model.res.nc
  hashes:
    binhash: 90dddf3e9274d87e82669cd17135c85d
    md5: abaa2b2513e70453d9d40dacd074aeed
work/INPUT/ice_model.res_1.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart008/ice_model.res_1.nc
  hashes:
    binhash: d2291a7b92b95a36880b6f70f0dd08bf
    md5: b15dc701d946927024884cfc74aec73b
