format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res.nc
  hashes:
    binhash: 740a2ee866b294293731c98ddaec578c
    md5: 41fbb84c07226afe27516994d5d2734c
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_1.nc
  hashes:
    binhash: 4b646293a9f61434a06209cce2dd0697
    md5: d26289acf7286a1e320cf105af0f9f88
work/INPUT/MOM.res_10.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_10.nc
  hashes:
    binhash: 2cd1b5e5c4114af9330ce755f7d51c9f
    md5: af628726f14d7e81a283ab10109209d1
work/INPUT/MOM.res_11.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_11.nc
  hashes:
    binhash: 47b1e62e621f22e4318ad1eadc7cf630
    md5: 89fb6e8a22ba1ae9412502ff32659297
work/INPUT/MOM.res_12.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_12.nc
  hashes:
    binhash: d3a9df95eade6bbed3042a54d6ffeb9e
    md5: adf7f5852114bfbc0cd7b7fff3d4920a
work/INPUT/MOM.res_13.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_13.nc
  hashes:
    binhash: 8dd5fb79cdb5b7c94110cd42c1bd09ba
    md5: 67a5b7196361293184977b51aeabce91
work/INPUT/MOM.res_14.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_14.nc
  hashes:
    binhash: 864b91257135cb6b44aec775bf28b8a0
    md5: 8aefb8e117a00672714fb016c5ca8899
work/INPUT/MOM.res_15.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_15.nc
  hashes:
    binhash: 08aef62e389297205c081e4a49d4abe9
    md5: a081eccb9422f0184c5e5d5ab34f8973
work/INPUT/MOM.res_16.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_16.nc
  hashes:
    binhash: 1680f043dd0cd0c0b0fd8b9c4c47f1be
    md5: 27296044cce030d03385c1f4b5cfab94
work/INPUT/MOM.res_17.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_17.nc
  hashes:
    binhash: c4f395b3baaa2a12871c5c88cd85489f
    md5: ee95cbb0ab09c37fb8f3fb39cc4a0834
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_2.nc
  hashes:
    binhash: 573c63fa0fb19f2d762997b6a16d9c72
    md5: 0b75e17e37f7392e6688bd4ef85fdcfe
work/INPUT/MOM.res_3.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_3.nc
  hashes:
    binhash: 5a4262645ce09bb26a1f7d514e467854
    md5: bc269c3f801ebb21cd95b7e27bc20dd5
work/INPUT/MOM.res_4.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_4.nc
  hashes:
    binhash: 6985201d69b388337813d05a2c7414ff
    md5: 175d2379fed9352ba6b164e334c87a0a
work/INPUT/MOM.res_5.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_5.nc
  hashes:
    binhash: f338471aceacf606f42c27e268cc8e49
    md5: 6af2ac5756cb98ce99c2f3b0117774d1
work/INPUT/MOM.res_6.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_6.nc
  hashes:
    binhash: 81b945ec0b4ae47fe3fecc405247b88b
    md5: d40b51564b87aaeec839258c6f20db13
work/INPUT/MOM.res_7.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_7.nc
  hashes:
    binhash: b7ef31744da188c4cdebd3ab64144b26
    md5: e5f77123a233939eb84475d97c3a098d
work/INPUT/MOM.res_8.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_8.nc
  hashes:
    binhash: ad2d97be490329443b3f96fe34b72626
    md5: 1089eb6813417bb0dc684ad70b5f5278
work/INPUT/MOM.res_9.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/MOM.res_9.nc
  hashes:
    binhash: bf00ca6f55810f4bc3d8b7a54bf49ac6
    md5: 0a1df87a97c9a658c2d77d1ea0e6d756
work/INPUT/Shelf.res.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/Shelf.res.nc
  hashes:
    binhash: b3c920f12bc478b3ae776f2ccb79d30e
    md5: 0dfb9a0ce937a6c41056fe0b89fd2e46
work/INPUT/coupler.res:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/coupler.res
  hashes:
    binhash: 092c4d909c01040cf317a3b152d8539f
    md5: d7fcb92b556983ce477ba43a61eb6588
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/ice_model.res.nc
  hashes:
    binhash: 4dcfb9e42b4ee3074f3347c446acd779
    md5: d7efe2c67a484b24221240beb72383d9
work/INPUT/ice_model.res_1.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-coldIC-1_12_IS_ALE_working_faster-4674602f/restart005/ice_model.res_1.nc
  hashes:
    binhash: 4eaa4957f7fee663edb347e961606c6a
    md5: 8cc0ab651e934dadf4ac48415bc1ad3a
