format: yamanifest
version: 1.0
---
work/INPUT/MOM.res.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res.nc
  hashes:
    binhash: e4a8b954e64bdbeca34b2669ed940fc4
    md5: 0adbdd557c5be26da7e02b1caaf5af47
work/INPUT/MOM.res_1.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_1.nc
  hashes:
    binhash: b3c0bd24e2025516b3290ab856d4a309
    md5: bbccb1f9f0ebaea1fb99fb2e6348d77b
work/INPUT/MOM.res_10.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_10.nc
  hashes:
    binhash: 4ee9f3b651b4a8d24329ced3948941fc
    md5: 3b5282184ae3d461c158db5ff131201e
work/INPUT/MOM.res_11.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_11.nc
  hashes:
    binhash: 57e27081c99902e9952f62ddeb6484e6
    md5: 49c779393266ccab8c676a211e73e8b2
work/INPUT/MOM.res_12.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_12.nc
  hashes:
    binhash: 8b4be8682fef77b5a8928fbb289be3c8
    md5: 25e5cd7a489832a4040a020ef77b7df5
work/INPUT/MOM.res_13.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_13.nc
  hashes:
    binhash: c6fda426a4e2a98b9bf06fc6c77eb850
    md5: 1c22ba81f8dd9fb79cd0dad290609f62
work/INPUT/MOM.res_14.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_14.nc
  hashes:
    binhash: db131c48128c7c5a3db751360edd1025
    md5: 830ab177a26bb8e7e59ba429098a8018
work/INPUT/MOM.res_15.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_15.nc
  hashes:
    binhash: 5e30c452b87cb84a92b67ba0eea4836f
    md5: f0743f8050d3138468cd9df8db6d1667
work/INPUT/MOM.res_16.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_16.nc
  hashes:
    binhash: 2f61a5802418b2bb8ef32b931045426c
    md5: c1bf238eb11f7df23d80b1651ebd6a15
work/INPUT/MOM.res_17.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_17.nc
  hashes:
    binhash: 45e32abbbad98dd87e4a971c9c2af3a6
    md5: 07c1ee96e4c792f9cb654987d70ce7cc
work/INPUT/MOM.res_2.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_2.nc
  hashes:
    binhash: b657fa87daee3465130de7a06902c1e9
    md5: 3536c182eecbf2ce5edb7a6413dc9ade
work/INPUT/MOM.res_3.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_3.nc
  hashes:
    binhash: 6120f82ce9a0d32a4e6c403e9fe74154
    md5: 9ca9e48b5c5176942cffd43e8e66b65d
work/INPUT/MOM.res_4.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_4.nc
  hashes:
    binhash: a429755e59e117d67452b37baa85b018
    md5: 4f7655622833a9d38b2d5d72c471669a
work/INPUT/MOM.res_5.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_5.nc
  hashes:
    binhash: a7a2c45e66db1b245bc396d34f2ce77f
    md5: 5dc73889711b6d5ec6c2fd447f11d3bf
work/INPUT/MOM.res_6.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_6.nc
  hashes:
    binhash: 671b217b4b6f70d794f6fb303ed65ba3
    md5: 4585267c502e62dbf222dd81678935a4
work/INPUT/MOM.res_7.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_7.nc
  hashes:
    binhash: a430634960c7b2494dfecf4277fbf1a0
    md5: 8cc6622ee6ad620113942fc388934a23
work/INPUT/MOM.res_8.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_8.nc
  hashes:
    binhash: 90eacf098868269dab806ebba84c1995
    md5: cdc3ea3a8d6f56d27beb6f346ee611e6
work/INPUT/MOM.res_9.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/MOM.res_9.nc
  hashes:
    binhash: 79607fdca833f25e7de74b3dce234ce0
    md5: f341641426d5a89a8948f54794e307b0
work/INPUT/Shelf.res.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/Shelf.res.nc
  hashes:
    binhash: a8d8f2309caf5f76987a296b3b479e38
    md5: 32f5ae25c1ae51d4dd3bcfd94d62743f
work/INPUT/coupler.res:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/coupler.res
  hashes:
    binhash: 3d9cbbfc3d8c93c9b8c9e2999e36bed6
    md5: 89b02ccb9ba39c58df9db07638f08192
work/INPUT/ice_model.res.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/ice_model.res.nc
  hashes:
    binhash: dfa91a27b2da59fb445787b5fc000e0c
    md5: cd5ba0aaa695bfb09fad7a44535dc90a
work/INPUT/ice_model.res_1.nc:
  fullpath: /scratch/x77/cy8964/mom6/archive/mom6-panan-2-testing-ALE-ACCESSOM2IC-1_12_IS_ALE_working_faster-6345ab85/restart017/ice_model.res_1.nc
  hashes:
    binhash: 321985fc3d78f7ab11dcdbfb4d612c71
    md5: de9a76ccfab5c25b05bfdf1add141d66
